# Generated by Django 5.1.5 on 2025-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
