# Generated by Django 5.1.5 on 2025-02-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer'), ('vendor', 'Vendor')], default='staff', max_length=20),
        ),
    ]
